### ISSUE TITLE
Erro no pgcomp-ufba.cls.

### ISSUE THREAD

**Issue by alcemirsantos** [PGCOMP-UFBA/pgcomp-ufba#5]
- Versão instalada: `pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)`
- Cliente LaTeX: _texlipse_

> \begin{pquot@tion} does not have matching end; at least one unbalanced begin-end ufbathesis.cls line 1124
> \begin{pquot@tion} does not have matching end; at least one unbalanced begin-end ufbathesis.cls line 653

ps: o erro não impede a compilação do documento via  `pdflatex` seja no cliente, seja na linha de comando.

**Comment by christinaflach** [comment]
Por que contents (sumario, lista de figuras, etc.) estão em vermelho? 
Está fora do padrão. Como resolver?

**Comment by alcemirsantos** [comment]
Era por conta dos links das referências cruzadas (criadas com a opção [scr] ) estarem utilizando as cores padrões do pacote.

Na pull request #6  eu adicionei o código pra mudar as cores pra preto.
